In [1]:
#Imports
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from scipy.stats import norm
from sklearn import preprocessing
from random import random

In [7]:
df = pd.read_csv("/Users/normalazo/Desktop/env1/Entrega2_Spam/spambase.data",header=None)

In [8]:
# This data does not have headers so each attribute or field is simply enumerated
df.describe()

0            1            2            3            4   \
count  4601.000000  4601.000000  4601.000000  4601.000000  4601.000000   
mean      0.104553     0.213015     0.280656     0.065425     0.312223   
std       0.305358     1.290575     0.504143     1.395151     0.672513   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.420000     0.000000     0.380000   
max       4.540000    14.280000     5.100000    42.810000    10.000000   

                5            6            7            8            9   \
count  4601.000000  4601.000000  4601.000000  4601.000000  4601.000000   
mean      0.095901     0.114208     0.105295     0.090067     0.239413   
std       0.273824     0.391441     0.401071     0.278616     0.644755   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.160000   
max       5.880000     7.270000    11.110000     5.260000    18.180000   

          ...                48           49           50           51  \
count     ...       4601.000000  4601.000000  4601.000000  4601.000000   
mean      ...          0.038575     0.139030     0.016976     0.269071   
std       ...          0.243471     0.270355     0.109394     0.815672   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          0.000000     0.065000     0.000000     0.000000   
75%       ...          0.000000     0.188000     0.000000     0.315000   
max       ...          4.385000     9.752000     4.081000    32.478000   

                52           53           54           55            56  \
count  4601.000000  4601.000000  4601.000000  4601.000000   4601.000000   
mean      0.075811     0.044238     5.191515    52.172789    283.289285   
std       0.245882     0.429342    31.729449   194.891310    606.347851   
min       0.000000     0.000000     1.000000     1.000000      1.000000   
25%       0.000000     0.000000     1.588000     6.000000     35.000000   
50%       0.000000     0.000000     2.276000    15.000000     95.000000   
75%       0.052000     0.000000     3.706000    43.000000    266.000000   
max       6.003000    19.829000  1102.500000  9989.000000  15841.000000   

                57  
count  4601.000000  
mean      0.394045  
std       0.488698  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000  

[8 rows x 58 columns]

In [9]:
# Here df.columns is a list of all the columns and df.columns[0:-1] is all columns minus the last which is y. 
# If the data had headers you could use column names: df[['column1','column2','etc']]
X_train, X_test, Y_train, Y_test = train_test_split(df[df.columns[0:-1]],df[df.columns[-1]], train_size=0.75)

/Users/normalazo/Desktop/env1/pythonEnv1/lib/python2.7/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [10]:
# index for selecting data 0.75 is the percentage in training
index=np.array([1 if random() < 0.75 else 0 for i in range(len(df))])


In [11]:
# Separate both train and test as well as the response variable
X_train=np.array(df[df.columns[0:-1]])[index==1]
X_test=np.array(df[df.columns[0:-1]])[index==0]
Y_train=np.array(df[df.columns[-1]])[index==1]
Y_test=np.array(df[df.columns[-1]])[index==0]

In [12]:
# Normalizar no ayuda mucho pero sale igual al de sklearn. Para que las alturas del pdf signifiquen lo mismo 
scaler = preprocessing.StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [13]:
X_train[Y_train==1]

array([[-0.35459636,  0.35343954,  0.72444607, ..., -0.04812385,
         0.03615081, -0.01787595],
       [ 0.34208544,  0.06192855,  0.44283146, ..., -0.00947766,
         0.22349298,  1.2450252 ],
       [-0.15554441, -0.16480222,  0.86525338, ...,  0.12447492,
         2.02197784,  3.31786694],
       ..., 
       [-0.35459636, -0.16480222, -0.56293503, ..., -0.08102149,
        -0.05283672, -0.17952729],
       [ 0.93924127, -0.16480222, -0.56293503, ..., -0.07703735,
        -0.1886598 , -0.36138506],
       [-0.35459636, -0.16480222, -0.56293503, ..., -0.03005292,
         0.05956858, -0.31592062]])

In [14]:
#Sacamos la media de cada una de las columnas.
#Cada elemento es la media de uno de las columnas

mediaS=np.mean(X_train[Y_train==1], axis=0)
dsS=np.std(X_train[Y_train==1], axis=0)
mediaNS=np.mean(X_train[Y_train==0], axis=0)
dsNS=np.std(X_train[Y_train==0], axis=0)

probS = mediaS[56]
probNS= 1-probS



In [15]:
def NaiveBayes(X_test,probS,mediaS, dsS,mediaNS, dsNS):
    
    #Probabilidad del caso base, que sea o no spam.
    probNS = 1 - probS
    spam = np.log(probS)
    noSpam = np.log(probNS)
    res = np.zeros((len(X_test),2))
    flag = np.zeros(len(X_test))

    
    #Tenemos que sumar las probabilidades condicionales asociadas a cada una de las variables
    
    for k in range (0, len(X_test)):
    
        for i in range (0, mediaS.size):
            p = norm.pdf(X_test[k][i], mediaS[i], dsS[i])
            if(p==0):
                spam+=-len(X_test)*100.0
            else:
                spam+=np.log(p)  
                
        res[k][0]=spam
        spam=0.0
        
        
        for j in range (0, mediaNS.size):
            pns = norm.pdf(X_test[k][j], mediaNS[j], dsNS[j])
            if(pns==0):
                noSpam+=-len(X_test)*100.0
            else:
                noSpam+=np.log(pns)

        res[k][1]=noSpam
        noSpam=0.0
        
        
        if(res[k][0] > res[k][1]):
            flag[k] = 1
        else:
            flag[k] = 0
            
        
    return flag
        
        

In [16]:
res = NaiveBayes(X_test,probS,mediaS, dsS,mediaNS, dsNS)

In [17]:
Y_test

array([1, 1, 1, ..., 0, 0, 0])

In [18]:
confusion_matrix(Y_test,res)

array([[501, 190],
       [ 27, 396]])

In [19]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
modelo = gnb.fit(X_train, Y_train)

In [20]:
confusion_matrix(Y_test,modelo.predict(X_test))

array([[501, 190],
       [ 29, 394]])